vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        #User
        users_avatar:
            uri_prefix: /erp/users/images
            upload_destination: '%kernel.project_dir%/public/erp/users/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

